services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: jobtracker-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Sagar@321
      MYSQL_DATABASE: jobtrackerdb
      MYSQL_USER: jobtracker
      MYSQL_PASSWORD: jobtracker123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jobtracker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: jobtracker-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jobtrackerdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Sagar@321
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8888:8888"
    networks:
      - jobtracker-network

  # React Frontend
  frontend:
    build: ./Frontend
    container_name: jobtracker-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - jobtracker-network

volumes:
  mysql_data:

networks:
  jobtracker-network:
    driver: bridge